/**
 * Cloudflare R2 Direct Client Upload Helper
 *
 * Facilitates direct browser-to-R2 uploads using short-lived presigned PUT URLs
 * generated by the Convex backend. The binary data never passes through Convex.
 */

export interface GeneratePresignedUrlResult {
  uploadUrl: string;
  storageKey: string;
  expiresAt: number;
  contentType: string;
}

export interface UploadFileToR2Options {
  file: File;
  assetType: string;
  generateUploadUrlAction: (args: {
    assetType: string;
    fileName: string;
    contentType: string;
    fileSize: number;
    organizationId?: string;
  }) => Promise<GeneratePresignedUrlResult>;
  organizationId?: string;
}

export interface UploadFileToR2Result {
  storageKey: string;
  uploadUrl: string;
  contentType: string;
}

/**
 * Uploads a file directly from the browser to Cloudflare R2 via a presigned PUT URL.
 *
 * @param options.file The File object selected in the browser.
 * @param options.assetType Category of the asset (e.g., 'logo', 'menu_image', 'invoice_pdf').
 * @param options.generateUploadUrlAction The Convex action invoker (e.g. useAction(api.r2.generateUploadUrl)).
 * @param options.organizationId Optional explicit organization ID (defaults to store organization).
 * @returns The generated R2 storageKey and upload metadata.
 */
export async function uploadFileToR2({
  file,
  assetType,
  generateUploadUrlAction,
  organizationId,
}: UploadFileToR2Options): Promise<UploadFileToR2Result> {
  if (!file) {
    throw new Error("No file provided for upload.");
  }

  const contentType = file.type || "application/octet-stream";

  // 1. Request short-lived presigned PUT URL from Convex backend
  const { uploadUrl, storageKey } = await generateUploadUrlAction({
    assetType,
    fileName: file.name,
    contentType,
    fileSize: file.size,
    organizationId,
  });

  if (!uploadUrl || !storageKey) {
    throw new Error("Invalid presigned URL response from backend.");
  }

  // 2. Direct HTTP PUT upload to Cloudflare R2 bucket
  const response = await fetch(uploadUrl, {
    method: "PUT",
    headers: {
      "Content-Type": contentType,
    },
    body: file,
  });

  if (!response.ok) {
    throw new Error(
      `Failed to upload file to storage: ${response.status} ${response.statusText}`
    );
  }

  return {
    storageKey,
    uploadUrl,
    contentType,
  };
}
